services:
  auth-service:
    build:
      context: .
      target: final
      args:
        - DB_HOST
        - DB_NAME
        - DB_USERNAME
        - DB_PASSWORD
    depends_on:
      db:
        condition: service_healthy
    networks:
      - kong-net

  db:
    image: postgres
    restart: always
    user: postgres
    volumes:
      - db-data:/var/lib/postgresql/data
    env_file:
      - .env
    expose:
      - 5432
    healthcheck:
      test: [ "CMD", "pg_isready" ]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - kong-net

volumes:
  db-data:
