volumes:
  public_key:

services:
  cronjob:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - public_key:/home/keys
    restart: on-failure
    depends_on:
      auth-service:
        condition: service_started
